name: Build

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  IS_CI: 'true'

jobs:
  Windows:
    name: Windows x64 Setup
    runs-on: windows-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Get npm cache directory
        shell: pwsh
        run: echo "NPM_CACHE=$(npm config get cache)" >> $env:GITHUB_ENV

      - name: Setup Node Env
        env:
          NPM_CACHE: ${{ env.NPM_CACHE }}
        uses: ./.github/actions/setup

      - name: Build src code
        run: |
          git status --porcelain
          npm run build

      - name: Build and publish x64 Setup
        run: npm run publish:win:setup:x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate file MD5
        run: |
          cd build
          Get-FileHash *.exe -Algorithm MD5 | Format-List

      - name: Upload Artifact Setup x64
        uses: actions/upload-artifact@v4
        with:
          name: ikun-music-desktop-x64-Setup
          path: build/*-x64-Setup.exe
